# Node.js with React
# Build with Node.js project that uses React.
# Add steps that anlyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipeline/language/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x' 
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
